apiVersion: v1
kind: Pod
metadata:
  name: run-as-group-containers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsGroup: 0
