apiVersion: v1
kind: Pod
metadata:
  name: procmount-containers
spec:
  hostUsers: false
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
    securityContext:
      procMount: Unmasked
