apiVersion: v1
kind: Pod
metadata:
  name: seccomp-profile-restricted-pod
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  securityContext:
    seccompProfile:
      type: Unconfined
