apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: apparmor-profile-pod
  annotations:
    security.kubeapt.io/displayName: 'Apparmor Profile'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for apparmor-profile.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the apparmor-profile policy.
    policies.kolteq.com/validatingAdmissionPolicy: 8b12778b-4d66-5b41-a3a5-fc73263509b2
  labels:
    apparmor-profile-pod.security.kolteq.com/audit: 'false,true'
    apparmor-profile-pod.security.kolteq.com/enforce: 'false,true'
    apparmor-profile-pod.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedAppArmorTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.appArmorProfile) ||
        !has(object.spec.securityContext.appArmorProfile.type) ||
        variables.allowedAppArmorTypes.exists(t, t == object.spec.securityContext.appArmorProfile.type)
      message: >
        spec.securityContext.appArmorProfile.type must be undefined, RuntimeDefault, or Localhost.
