apiVersion: v1
kind: Pod
metadata:
  name: violating-share-process-namespace
spec:
  shareProcessNamespace: true
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
