apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: run-as-group-initcontainers
  annotations:
    security.kubeapt.io/displayName: 'Run As Group'
    security.kubeapt.io/description: spec.initContainers[*].securityContext.runAsGroup must be undefined or a non-zero value
    security.kubeapt.io/resource: Initcontainers
    security.kubeapt.io/severity: "6"
    security.kubeapt.io/remediation: "Set spec.initContainers[*].securityContext.runAsGroup to >0 or omit it. Fields: spec.initContainers[*].securityContext.runAsGroup."
    policies.kolteq.com/validatingAdmissionPolicy: de80408d-f5d5-59bf-a38a-77a8452d4934
  labels:
    check-run-as-group-initcontainers.security.kolteq.com/audit: 'false-true'
    check-run-as-group-initcontainers.security.kolteq.com/enforce: 'false-true'
    check-run-as-group-initcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.initContainers) || object.spec.initContainers.all(ic,
        !has(ic.securityContext) ||
        !has(ic.securityContext.runAsGroup) ||
        ic.securityContext.runAsGroup > 0
      )
    message: |
      spec.initContainers[*].securityContext.runAsGroup must be undefined or a non-zero value (> 0).
