apiVersion: v1
kind: Pod
metadata:
  name: read-only-root-filesystem-ephemeralcontainers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
---
# Command: kubectl debug -n policy-test read-only-root-filesystem-ephemeralcontainers -it --image=busybox:1.36 --custom=policies/read-only-root-filesystem/ephemeralcontainers/test-kubectl-debug-custom.yaml
