apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: violating-tls-required
spec:
  tls:
  - hosts:
    - app.example.com
    secretName: tls-app
  - hosts:
    - api.example.com
    secretName: tls-api
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 80
  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo
            port:
              number: 80
