apiVersion: v1
kind: Pod
metadata:
  name: readinessprobe-tcpsocket-host-initcontainers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  initContainers:
  - name: init
    image: busybox:1.36
    command:
    - sh
    - -c
    - echo init
    restartPolicy: Always
    readinessProbe:
      tcpSocket:
        port: 80
        host: 127.0.0.1
