apiVersion: v1
kind: Pod
metadata:
  name: capabilities-drop-all-initcontainers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  initContainers:
  - name: init
    image: busybox:1.36
    command:
    - sh
    - -c
    - echo init
    securityContext:
      capabilities:
        drop:
        - NET_RAW
