apiVersion: v1
kind: Pod
metadata:
  name: startupprobe-tcpsocket-host-containers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
    startupProbe:
      tcpSocket:
        port: 80
        host: 127.0.0.1
