apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: selinux-type-containers
  annotations:
    security.kubeapt.io/displayName: "Selinux Type"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for selinux-type/containers."
    security.kubeapt.io/resource: "Containers"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the selinux-type/containers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  variables:
  - name: allowedSELinuxTypes
    expression: |
      ["container_t","container_init_t","container_kvm_t","container_engine_t"]
  validations:
  - expression: |
      object.spec.containers.all(c,
        !has(c.securityContext) ||
        !has(c.securityContext.seLinuxOptions) ||
        !has(c.securityContext.seLinuxOptions.type) ||
        c.securityContext.seLinuxOptions.type == "" ||
        variables.allowedSELinuxTypes.exists(t, t == c.securityContext.seLinuxOptions.type)
      )
    message: |
      spec.containers[*].securityContext.seLinuxOptions.type must be undefined, empty (""), or one of: container_t, container_init_t, container_kvm_t, container_engine_t.
