apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/warn: enabled
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-networkpolicy-allow-all.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-networkpolicy-allow-all.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    security.kolteq.com/audit: enabled
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-networkpolicy-allow-all.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-networkpolicy-allow-all.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optout-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/enforce: enabled
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-networkpolicy-allow-all.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: networkpolicy-allow-all-namespace-optin-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4e1aaa89-d6ce-5c0b-a31c-b3de55b5e517
  labels:
    check-networkpolicy-allow-all.security.kolteq.com/enforce: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/audit: 'false-true'
    check-networkpolicy-allow-all.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: networkpolicy-allow-all
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-networkpolicy-allow-all.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
