apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: prestop-httpget-host-containers
  annotations:
    security.kubeapt.io/displayName: 'Prestop Httpget Host'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for prestop-httpget-host/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the prestop-httpget-host/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 9a7503f9-b67d-54d3-9dd8-997c792c8d5b
  labels:
    prestop-httpget-host-containers.security.kolteq.com/audit: 'false - true'
    prestop-httpget-host-containers.security.kolteq.com/enforce: 'false - true'
    prestop-httpget-host-containers.security.kolteq.com/warn: 'false - true'
    pss.security.kolteq.com/audit: 'baseline - restricted'
    pss.security.kolteq.com/enforce: 'baseline - restricted'
    pss.security.kolteq.com/warn: 'baseline - restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.lifecycle) ||
          !has(c.lifecycle.preStop) ||
          !has(c.lifecycle.preStop.httpGet) ||
          !has(c.lifecycle.preStop.httpGet.host) ||
          c.lifecycle.preStop.httpGet.host == ""
        )
      message: >
        spec.containers[*].lifecycle.preStop.httpGet.host must be undefined or empty ("").
