apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: selinux-user
  annotations:
    security.kubeapt.io/displayName: 'Selinux User'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for selinux-user.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the selinux-user policy.
    policies.kolteq.com/validatingAdmissionPolicy: 678216cd-a01a-5f28-a28e-9a17e5993fbe
  labels:
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
    selinux-user.security.kolteq.com/audit: 'false,true'
    selinux-user.security.kolteq.com/enforce: 'false,true'
    selinux-user.security.kolteq.com/warn: 'false,true'
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.seLinuxOptions) ||
        !has(object.spec.securityContext.seLinuxOptions.user) ||
        object.spec.securityContext.seLinuxOptions.user == ""
      message: >
        spec.securityContext.seLinuxOptions.user must be undefined or an empty string ("").
