apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: selinux-user-containers
  annotations:
    security.kubeapt.io/displayName: 'Selinux User'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for selinux-user/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the selinux-user/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: ad70fa8b-f5ef-55ca-ba3f-bad9a3c3145c
  labels:
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
    selinux-user-containers.security.kolteq.com/audit: 'false,true'
    selinux-user-containers.security.kolteq.com/enforce: 'false,true'
    selinux-user-containers.security.kolteq.com/warn: 'false,true'
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.seLinuxOptions) ||
          !has(c.securityContext.seLinuxOptions.user) ||
          c.securityContext.seLinuxOptions.user == ""
        )
      message: >
        spec.containers[*].securityContext.seLinuxOptions.user must be undefined or an empty string ("").
