apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/warn: enabled
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-configmap-data-classification-label.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-configmap-data-classification-label.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    security.kolteq.com/audit: enabled
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-configmap-data-classification-label.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-configmap-data-classification-label.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optout-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    security.kolteq.com/enforce: enabled
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-configmap-data-classification-label.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: configmap-data-classification-label-namespace-optin-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9c061faa-00a5-550e-84d0-8fc2d3fd74d6
  labels:
    check-configmap-data-classification-label.security.kolteq.com/enforce: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/audit: 'false,true'
    check-configmap-data-classification-label.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: configmap-data-classification-label
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-configmap-data-classification-label.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
