apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: poststart-httpget-host-containers
  annotations:
    security.kubeapt.io/displayName: 'Poststart Httpget Host'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for poststart-httpget-host/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the poststart-httpget-host/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 61951dbe-b3f2-51f3-9c31-e89becf09777
  labels:
    poststart-httpget-host-containers.security.kolteq.com/audit: 'false,true'
    poststart-httpget-host-containers.security.kolteq.com/enforce: 'false,true'
    poststart-httpget-host-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.lifecycle) ||
          !has(c.lifecycle.postStart) ||
          !has(c.lifecycle.postStart.httpGet) ||
          !has(c.lifecycle.postStart.httpGet.host) ||
          c.lifecycle.postStart.httpGet.host == ""
        )
      message: >
        spec.containers[*].lifecycle.postStart.httpGet.host must be undefined or empty ("").
