apiVersion: v1
kind: Pod
metadata:
  name: apparmor-profile-containers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
    securityContext:
      appArmorProfile:
        type: Unconfined
