apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/warn: enabled
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-containers.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-containers.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    security.kolteq.com/audit: enabled
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-containers.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-containers.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/enforce: enabled
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-containers.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-containers-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: d0774f8f-2e4c-5b28-9f67-18c98a757dde
  labels:
    check-image-no-latest-containers.security.kolteq.com/enforce: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/audit: 'false - true'
    check-image-no-latest-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-containers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-containers.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
