apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: privileged-containers
  annotations:
    security.kubeapt.io/displayName: Privileged
    security.kubeapt.io/description: ValidatingAdmissionPolicy for privileged/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: Adjust workloads to satisfy the privileged/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: f0ca8163-6be7-5de8-b2c8-eadc6f4a146e
  labels:
    privileged-containers.security.kolteq.com/audit: 'false-true'
    privileged-containers.security.kolteq.com/enforce: 'false-true'
    privileged-containers.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.privileged) ||
          c.securityContext.privileged == false
        )
      message: >
        Privileged containers are disallowed. All
        spec.containers[*].securityContext.privileged must be undefined or false.
