apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: hostpid
  annotations:
    security.kubeapt.io/displayName: Hostpid
    security.kubeapt.io/description: ValidatingAdmissionPolicy for hostpid.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the hostpid policy.
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/audit: 'false,true'
    hostpid.security.kolteq.com/enforce: 'false,true'
    hostpid.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.hostPID) || object.spec.hostPID == false
      message: >
        Using hostPID is disallowed. spec.hostPID must be undefined or set to false.
