apiVersion: v1
kind: Pod
metadata:
  name: capabilities-add-containers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
    securityContext:
      capabilities:
        add:
        - SYS_ADMIN
