apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: pod-template-labels
  annotations:
    security.kubeapt.io/displayName: "Pod Template Labels"
    security.kubeapt.io/description: "Pods must set metadata.labels (non-empty) for policy targeting."
    security.kubeapt.io/resource: "Pods"
    security.kubeapt.io/severity: "3"
    security.kubeapt.io/remediation: "Add at least one label to metadata.labels. Fields: metadata.labels."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      has(object.metadata.labels) && size(object.metadata.labels) > 0
    message: |
      Pods must set metadata.labels (non-empty) for policy targeting.
