apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: hostipc
  annotations:
    security.kubeapt.io/displayName: Hostipc
    security.kubeapt.io/description: ValidatingAdmissionPolicy for hostipc.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the hostipc policy.
    policies.kolteq.com/validatingAdmissionPolicy: 5857de86-e1f4-5b68-a0ba-30b370f12dc5
  labels:
    hostipc.security.kolteq.com/audit: 'false - true'
    hostipc.security.kolteq.com/enforce: 'false - true'
    hostipc.security.kolteq.com/warn: 'false - true'
    pss.security.kolteq.com/audit: 'baseline - restricted'
    pss.security.kolteq.com/enforce: 'baseline - restricted'
    pss.security.kolteq.com/warn: 'baseline - restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.hostIPC) || object.spec.hostIPC == false
      message: >
        Using hostIPC is disallowed. spec.hostIPC must be undefined or set to false.
