apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: violating-rolebinding-powerful-role
subjects:
- kind: User
  name: alice
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
