apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: allowed-hostports-containers
  annotations:
    security.kubeapt.io/displayName: "Hostports"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for hostports/containers."
    security.kubeapt.io/resource: "Containers"
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the hostports/containers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  variables:
  - name: allowedHostPorts
    expression: |
      []
  validations:
  - expression: |
      object.spec.containers.all(c,
        !has(c.ports) ||
        c.ports.all(p,
          !has(p.hostPort) ||
          p.hostPort == 0 ||
          variables.allowedHostPorts.exists(h, h == p.hostPort)
        )
      )
    message: |
      hostPort must be undefined, 0, or in the variables.allowedHostPorts list.
