apiVersion: v1
kind: Pod
metadata:
  name: violating-automount-service-account-token
spec:
  automountServiceAccountToken: true
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
