apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: selinux-user
  annotations:
    security.kubeapt.io/displayName: "Selinux User"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for selinux-user."
    security.kubeapt.io/resource: "Pods"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the selinux-user policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.securityContext) || !has(object.spec.securityContext.seLinuxOptions) || !has(object.spec.securityContext.seLinuxOptions.user) || object.spec.securityContext.seLinuxOptions.user == ""
    message: |
      spec.securityContext.seLinuxOptions.user must be undefined or an empty string ("").
