apiVersion: v1
kind: Pod
metadata:
  name: apparmor-annotation-values-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/main: unconfined
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
