apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: run-as-user-initcontainers
  annotations:
    security.kubeapt.io/displayName: "Run As User"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for run-as-user/initcontainers."
    security.kubeapt.io/resource: "Initcontainers"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the run-as-user/initcontainers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.initContainers) || object.spec.initContainers.all(ic,
        !has(ic.securityContext) ||
        !has(ic.securityContext.runAsUser) ||
        ic.securityContext.runAsUser > 0
      )
    message: |
      spec.initContainers[*].securityContext.runAsUser must be undefined or a non-zero value (> 0).
