apiVersion: v1
kind: Pod
metadata:
  name: run-as-user-initcontainers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  initContainers:
  - name: init
    image: busybox:1.36
    command:
    - sh
    - -c
    - echo init
    securityContext:
      runAsUser: 0
