apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: rolebinding-system-groups
  annotations:
    security.kubeapt.io/displayName: 'System Groups'
    security.kubeapt.io/description: RoleBindings must not bind powerful roles to broad system groups (authenticated/unauthenticated/serviceaccounts).
    security.kubeapt.io/resource: RoleBindings
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Avoid binding broad system groups; use specific groups. Fields: subjects[*].kind, subjects[*].name."
    policies.kolteq.com/validatingAdmissionPolicy: cc396951-a7b9-533f-a1c9-213f44798c41
  labels:
    check-rolebinding-system-groups.security.kolteq.com/audit: 'false-true'
    check-rolebinding-system-groups.security.kolteq.com/enforce: 'false-true'
    check-rolebinding-system-groups.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - rolebindings
  variables:
  - name: riskyGroups
    expression: |
      ["system:authenticated","system:unauthenticated","system:serviceaccounts"]
  validations:
  - expression: |
      !has(object.subjects) || object.subjects.all(s,
        !(s.kind == "Group" && variables.riskyGroups.exists(g, g == s.name))
      )
    message: |
      RoleBindings must not bind powerful roles to broad system groups (authenticated/unauthenticated/serviceaccounts).
