apiVersion: v1
kind: Pod
metadata:
  name: procmount-initcontainers
spec:
  hostUsers: false
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  initContainers:
  - name: init
    image: busybox:1.36
    command:
    - sh
    - -c
    - echo init
    securityContext:
      procMount: Unmasked
