apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: capabilities-drop-all-containers
  annotations:
    security.kubeapt.io/displayName: 'Capabilities Drop All'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for capabilities-drop-all/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: Adjust workloads to satisfy the capabilities-drop-all/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 375a0615-9a42-526c-9f37-6e5f4c920876
  labels:
    capabilities-drop-all-containers.security.kolteq.com/audit: 'false-true'
    capabilities-drop-all-containers.security.kolteq.com/enforce: 'false-true'
    capabilities-drop-all-containers.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        object.spec.containers.all(c,
          has(c.securityContext) &&
          has(c.securityContext.capabilities) &&
          has(c.securityContext.capabilities.drop) &&
          c.securityContext.capabilities.drop.exists(d, d == "ALL")
        )
      message: >
        spec.containers[*].securityContext.capabilities.drop must exist and include "ALL".
