apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-warn-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/warn
        operator: In
        values:
        - baseline
        - restricted
      - key: run-as-user-pod.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/warn: enabled
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: run-as-user-pod.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: run-as-user-pod.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-audit-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    pss.security.kolteq.com/audit: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/audit
        operator: In
        values:
        - baseline
        - restricted
      - key: run-as-user-pod.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    security.kolteq.com/audit: enabled
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: run-as-user-pod.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: run-as-user-pod.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-deny-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/enforce
        operator: In
        values:
        - baseline
        - restricted
      - key: run-as-user-pod.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/enforce: enabled
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: run-as-user-pod.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: run-as-user-pod-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 08819adb-4c93-5b34-9fd4-99e5b7087cf4
  labels:
    run-as-user-pod.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    run-as-user-pod.security.kolteq.com/audit: 'false-true'
    run-as-user-pod.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: run-as-user-pod
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: run-as-user-pod.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
