apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: run-as-user-pod
  annotations:
    security.kubeapt.io/displayName: "Run As User"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for run-as-user."
    security.kubeapt.io/resource: "Pods"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the run-as-user policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.securityContext) || !has(object.spec.securityContext.runAsUser) || object.spec.securityContext.runAsUser > 0
    message: |
      spec.securityContext.runAsUser must be undefined or a non-zero value (> 0).
