apiVersion: v1
kind: Pod
metadata:
  name: run-as-user-pod
spec:
  containers:
  - name: main
    image: busybox:1.36
    command:
    - sh
    - -c
    - sleep 3600
  securityContext:
    runAsUser: 0
