apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-warn-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/warn
        operator: In
        values:
        - baseline
        - restricted
      - key: hostpid.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/warn: enabled
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: hostpid
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: hostpid.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/warn: 'false-true'
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: hostpid.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-audit-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/audit: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    hostpid.security.kolteq.com/enforce: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/audit
        operator: In
        values:
        - baseline
        - restricted
      - key: hostpid.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/audit: 'false-true'
    security.kolteq.com/audit: enabled
    hostpid.security.kolteq.com/enforce: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: hostpid.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/enforce: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: hostpid.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-deny-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/enforce: 'false-true'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/enforce
        operator: In
        values:
        - baseline
        - restricted
      - key: hostpid.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/enforce: enabled
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: hostpid.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: hostpid-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 47ac01eb-7758-5d32-b024-8d280b0277d4
  labels:
    hostpid.security.kolteq.com/enforce: 'false-true'
    hostpid.security.kolteq.com/audit: 'false-true'
    hostpid.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: hostpid
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: hostpid.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
