apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: livenessprobe-httpget-host-initcontainers
  annotations:
    security.kubeapt.io/displayName: 'Livenessprobe Httpget Host'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for livenessprobe-httpget-host/initcontainers.
    security.kubeapt.io/resource: Initcontainers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the livenessprobe-httpget-host/initcontainers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 32cab35f-b5d0-5896-a5e6-7c5ac722ffd0
  labels:
    livenessprobe-httpget-host-initcontainers.security.kolteq.com/audit: 'false,true'
    livenessprobe-httpget-host-initcontainers.security.kolteq.com/enforce: 'false,true'
    livenessprobe-httpget-host-initcontainers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.livenessProbe) ||
          !has(ic.livenessProbe.httpGet) ||
          !has(ic.livenessProbe.httpGet.host) ||
          ic.livenessProbe.httpGet.host == ""
        )
      message: >
        spec.initContainers[*].livenessProbe.httpGet.host must be undefined or empty ("").
