apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: run-as-nonroot-initcontainers
  annotations:
    security.kubeapt.io/displayName: "Run As Nonroot"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for run-as-nonroot/initcontainers."
    security.kubeapt.io/resource: "Initcontainers"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the run-as-nonroot/initcontainers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  variables:
  - name: podNonRootTrue
    expression: |
      has(object.spec.securityContext) && has(object.spec.securityContext.runAsNonRoot) && object.spec.securityContext.runAsNonRoot == true
  validations:
  - expression: |
      !has(object.spec.initContainers) || object.spec.initContainers.all(ic,
        variables.podNonRootTrue
        ? (!has(ic.securityContext) || !has(ic.securityContext.runAsNonRoot) || ic.securityContext.runAsNonRoot == true)
        : (has(ic.securityContext) && has(ic.securityContext.runAsNonRoot) && ic.securityContext.runAsNonRoot == true)
      )
    message: "spec.initContainers[*].securityContext.runAsNonRoot must be set to true, unless the Pod-level spec.securityContext.runAsNonRoot is true\u2014in which case it may be undefined or true.\n"
