apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: configmap-no-executable-code
  annotations:
    security.kubeapt.io/displayName: 'No Executable Code'
    security.kubeapt.io/description: Do not store executable code or scripts in ConfigMaps that applications run.
    security.kubeapt.io/resource: ConfigMaps
    security.kubeapt.io/severity: "7"
    security.kubeapt.io/remediation: "Remove executable code/scripts from ConfigMap data; bake into image or volume. Fields: data."
    policies.kolteq.com/validatingAdmissionPolicy: 7e9b70e6-e20d-5bbb-9069-03a99ebb5489
  labels:
    check-configmap-no-executable-code.security.kolteq.com/audit: 'false - true'
    check-configmap-no-executable-code.security.kolteq.com/enforce: 'false - true'
    check-configmap-no-executable-code.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - configmaps
  validations:
  - expression: |
      !has(object.data) || !object.data.exists(
        k,
        v,
        k.lowerAscii().matches(".*\\.(sh|bash|py|lua|js|ts|rb|pl|php|groovy|tmpl)$") ||
        v.matches("(?s).*#!/\\S+") ||
        v.matches("(?i).*\\b(function|import|require|process|exec)\\b.*")
      )
    message: |
      Do not store executable code or scripts in ConfigMaps that applications run.
