apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: seccomp-profile-ephemeralcontainers
  annotations:
    security.kubeapt.io/displayName: 'Seccomp Profile'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for seccomp-profile/ephemeralcontainers.
    security.kubeapt.io/resource: Ephemeralcontainers
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: Adjust workloads to satisfy the seccomp-profile/ephemeralcontainers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 73385630-a5c8-57c6-82cc-e51971f02c92
  labels:
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    seccomp-profile-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    seccomp-profile-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    seccomp-profile-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods/ephemeralcontainers"]
  variables:
    - name: allowedSeccompTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.ephemeralContainers) ||
        object.spec.ephemeralContainers.all(ec,
          !has(ec.securityContext) ||
          !has(ec.securityContext.seccompProfile) ||
          !has(ec.securityContext.seccompProfile.type) ||
          variables.allowedSeccompTypes.exists(t, t == ec.securityContext.seccompProfile.type)
        )
      message: >
        spec.ephemeralContainers[*].securityContext.seccompProfile.type must be undefined, RuntimeDefault, or Localhost.
