apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/warn: enabled
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    security.kolteq.com/audit: enabled
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optout-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/enforce: enabled
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: ingress-no-dangerous-snippets-namespace-optin-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 717a3ee4-314c-5faa-baa1-9b13cda9b236
  labels:
    check-ingress-no-dangerous-snippets.security.kolteq.com/enforce: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/audit: 'false-true'
    check-ingress-no-dangerous-snippets.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: ingress-no-dangerous-snippets
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-ingress-no-dangerous-snippets.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
