apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/warn: enabled
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-automount-service-account-token.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-automount-service-account-token.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    security.kolteq.com/audit: enabled
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-automount-service-account-token.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-automount-service-account-token.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    security.kolteq.com/enforce: enabled
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-automount-service-account-token.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: automount-service-account-token-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 9f1a7c24-c2ac-5b28-bcc2-a73b739031bc
  labels:
    check-automount-service-account-token.security.kolteq.com/enforce: 'false - true'
    check-automount-service-account-token.security.kolteq.com/audit: 'false - true'
    check-automount-service-account-token.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: automount-service-account-token
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-automount-service-account-token.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
