apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: hostusers
  annotations:
    security.kubeapt.io/displayName: Hostusers
    security.kubeapt.io/description: Using hostUsers is disallowed. spec.hostUsers must be undefined or set to false.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Set spec.hostUsers=false or omit it. Fields: spec.hostUsers."
    policies.kolteq.com/validatingAdmissionPolicy: ef824444-e21d-5f0c-8b9e-58ae3fba230b
  labels:
    check-hostusers.security.kolteq.com/audit: 'false-true'
    check-hostusers.security.kolteq.com/enforce: 'false-true'
    check-hostusers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.hostUsers) || object.spec.hostUsers == false
    message: |
      Using hostUsers is disallowed. spec.hostUsers must be undefined or set to false.
