apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: seccomp-profile-containers
  annotations:
    security.kubeapt.io/displayName: 'Seccomp Profile'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for seccomp-profile/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: Adjust workloads to satisfy the seccomp-profile/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 500d2ca8-f835-5884-a1e7-0b604c1344c8
  labels:
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    seccomp-profile-containers.security.kolteq.com/audit: 'false-true'
    seccomp-profile-containers.security.kolteq.com/enforce: 'false-true'
    seccomp-profile-containers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedSeccompTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.seccompProfile) ||
          !has(c.securityContext.seccompProfile.type) ||
          variables.allowedSeccompTypes.exists(t, t == c.securityContext.seccompProfile.type)
        )
      message: >
        spec.containers[*].securityContext.seccompProfile.type must be undefined, RuntimeDefault, or Localhost.
