apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: hostpath-volumes
  annotations:
    security.kubeapt.io/displayName: "Hostpath Volumes"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for hostpath-volumes."
    security.kubeapt.io/resource: "Pods"
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the hostpath-volumes policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.volumes) || object.spec.volumes.all(v, !has(v.hostPath))
    message: |
      HostPath volumes are disallowed. Each spec.volumes[*].hostPath must be undefined.
