apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Warn
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Warn
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Audit
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Audit
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optout-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Deny
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: namespace-pod-security-standards-namespace-optin-enforce
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 4a27053d-9597-5c16-b85f-23e97f2c2ec3
spec:
  policyName: namespace-pod-security-standards
  validationActions:
  - Deny
