apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: serviceaccount-token-projection
  annotations:
    security.kubeapt.io/displayName: 'Serviceaccount Token Projection'
    security.kubeapt.io/description: Pods using a serviceAccountName must include a projected serviceAccountToken volume.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: "6"
    security.kubeapt.io/remediation: "Add projected serviceAccountToken volume when using serviceAccountName. Fields: spec.serviceAccountName, spec.volumes[].projected.sources[].serviceAccountToken."
    policies.kolteq.com/validatingAdmissionPolicy: 84b2a590-8503-5c53-bde9-96ff9c294616
  labels:
    check-serviceaccount-token-projection.security.kolteq.com/audit: 'false-true'
    check-serviceaccount-token-projection.security.kolteq.com/enforce: 'false-true'
    check-serviceaccount-token-projection.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.serviceAccountName) || (has(object.spec.volumes) &&
       object.spec.volumes.exists(v,
         has(v.projected) &&
         has(v.projected.sources) &&
         v.projected.sources.exists(s, has(s.serviceAccountToken))
       ))
    message: |
      Pods using a serviceAccountName must include a projected serviceAccountToken volume.
