apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: selinux-user-ephemeralcontainers
  annotations:
    security.kubeapt.io/displayName: 'Selinux User'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for selinux-user/ephemeralcontainers.
    security.kubeapt.io/resource: Ephemeralcontainers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the selinux-user/ephemeralcontainers policy.
    policies.kolteq.com/validatingAdmissionPolicy: c7406e3b-0b35-5689-aca3-2661d8698786
  labels:
    pss.security.kolteq.com/audit: 'baseline - restricted'
    pss.security.kolteq.com/enforce: 'baseline - restricted'
    pss.security.kolteq.com/warn: 'baseline - restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
    selinux-user-ephemeralcontainers.security.kolteq.com/audit: 'false - true'
    selinux-user-ephemeralcontainers.security.kolteq.com/enforce: 'false - true'
    selinux-user-ephemeralcontainers.security.kolteq.com/warn: 'false - true'
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods/ephemeralcontainers"]
  validations:
    - expression: >
        !has(object.spec.ephemeralContainers) ||
        object.spec.ephemeralContainers.all(ec,
          !has(ec.securityContext) ||
          !has(ec.securityContext.seLinuxOptions) ||
          !has(ec.securityContext.seLinuxOptions.user) ||
          ec.securityContext.seLinuxOptions.user == ""
        )
      message: >
        spec.ephemeralContainers[*].securityContext.seLinuxOptions.user must be undefined or an empty string ("").
