apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: serviceaccount-automount-token-false
  annotations:
    security.kubeapt.io/displayName: "Automount Token False"
    security.kubeapt.io/description: "automountServiceAccountToken must be set to false by default on ServiceAccounts."
    security.kubeapt.io/resource: "ServiceAccounts"
    security.kubeapt.io/severity: "3"
    security.kubeapt.io/remediation: "Set automountServiceAccountToken=false on ServiceAccounts. Fields: automountServiceAccountToken."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - serviceaccounts
  validations:
  - expression: |
      has(object.automountServiceAccountToken) && object.automountServiceAccountToken == false
    message: |
      automountServiceAccountToken must be set to false by default on ServiceAccounts.
