apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: violating-clusterrole-aggregation
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.example.io/aggregate: "true"
