apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-warn-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/warn
        operator: In
        values:
        - baseline
        - restricted
      - key: allow-privilege-escalation-containers.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    security.kolteq.com/warn: enabled
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: allow-privilege-escalation-containers.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: allow-privilege-escalation-containers.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-audit-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/audit
        operator: In
        values:
        - baseline
        - restricted
      - key: allow-privilege-escalation-containers.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    security.kolteq.com/audit: enabled
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: allow-privilege-escalation-containers.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: allow-privilege-escalation-containers.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-deny-pss
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: pss.security.kolteq.com/enforce
        operator: In
        values:
        - baseline
        - restricted
      - key: allow-privilege-escalation-containers.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    security.kolteq.com/enforce: enabled
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: allow-privilege-escalation-containers.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: allow-privilege-escalation-containers-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: b5df7f0d-aef7-531f-84bc-b07c9b9f73ef
  labels:
    allow-privilege-escalation-containers.security.kolteq.com/enforce: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/audit: 'false,true'
    allow-privilege-escalation-containers.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: allow-privilege-escalation-containers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: allow-privilege-escalation-containers.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
