apiVersion: v1
kind: Pod
metadata:
  name: read-only-root-filesystem-containers
spec:
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      readOnlyRootFilesystem: false
