apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: windows-hostprocess-initcontainers
  annotations:
    security.kubeapt.io/displayName: "Windows Hostprocess"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for windows-hostprocess/initcontainers."
    security.kubeapt.io/resource: "Initcontainers"
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the windows-hostprocess/initcontainers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.initContainers) || object.spec.initContainers.all(c,
        !has(c.securityContext) ||
        !has(c.securityContext.windowsOptions) ||
        !has(c.securityContext.windowsOptions.hostProcess) ||
        c.securityContext.windowsOptions.hostProcess == false
      )
    message: |
      HostProcess is not allowed for initContainers. Each spec.initContainers[*].securityContext.windowsOptions.hostProcess must be undefined or set to false.
