apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: windows-hostprocess-containers
  annotations:
    security.kubeapt.io/displayName: 'Windows Hostprocess'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for windows-hostprocess/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the windows-hostprocess/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 24454df4-1625-5aa1-b0f1-ce92e28e9672
  labels:
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
    windows-hostprocess-containers.security.kolteq.com/audit: 'false-true'
    windows-hostprocess-containers.security.kolteq.com/enforce: 'false-true'
    windows-hostprocess-containers.security.kolteq.com/warn: 'false-true'
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.windowsOptions) ||
          !has(c.securityContext.windowsOptions.hostProcess) ||
          c.securityContext.windowsOptions.hostProcess == false
        )
      message: >
        HostProcess is not allowed for containers. Each spec.containers[*].securityContext.windowsOptions.hostProcess must be undefined or set to false.
