apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: readinessprobe-tcpsocket-host-initcontainers
  annotations:
    security.kubeapt.io/displayName: 'Readinessprobe Tcpsocket Host'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for readinessprobe-tcpsocket-host/initcontainers.
    security.kubeapt.io/resource: Initcontainers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the readinessprobe-tcpsocket-host/initcontainers policy.
    policies.kolteq.com/validatingAdmissionPolicy: 092890ca-2c4e-527e-a91a-07666733b2c6
  labels:
    pss.security.kolteq.com/audit: 'baseline - restricted'
    pss.security.kolteq.com/enforce: 'baseline - restricted'
    pss.security.kolteq.com/warn: 'baseline - restricted'
    readinessprobe-tcpsocket-host-initcontainers.security.kolteq.com/audit: 'false - true'
    readinessprobe-tcpsocket-host-initcontainers.security.kolteq.com/enforce: 'false - true'
    readinessprobe-tcpsocket-host-initcontainers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.readinessProbe) ||
          !has(ic.readinessProbe.tcpSocket) ||
          !has(ic.readinessProbe.tcpSocket.host) ||
          ic.readinessProbe.tcpSocket.host == ""
        )
      message: >
        spec.initContainers[*].readinessProbe.tcpSocket.host must be undefined or empty ("").
