apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: privileged-ephemeralcontainers
  annotations:
    security.kubeapt.io/displayName: "Privileged"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for privileged/ephemeralcontainers."
    security.kubeapt.io/resource: "Ephemeralcontainers"
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the privileged/ephemeralcontainers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods/ephemeralcontainers
  validations:
  - expression: |
      (has(object.spec.os) &&
       has(object.spec.os.name) &&
       object.spec.os.name.lowerAscii() == "windows") ||
      !has(object.spec.ephemeralContainers) || object.spec.ephemeralContainers.all(c,
        !has(c.securityContext) ||
        !has(c.securityContext.privileged) ||
        c.securityContext.privileged == false
      )
    message: |
      Privileged ephemeral containers are disallowed. All spec.ephemeralContainers[*].securityContext.privileged must be undefined or false.
