apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: privileged-ephemeralcontainers
  annotations:
    security.kubeapt.io/displayName: Privileged
    security.kubeapt.io/description: ValidatingAdmissionPolicy for privileged/ephemeralcontainers.
    security.kubeapt.io/resource: Ephemeralcontainers
    security.kubeapt.io/severity: "10"
    security.kubeapt.io/remediation: Adjust workloads to satisfy the privileged/ephemeralcontainers policy.
    policies.kolteq.com/validatingAdmissionPolicy: e7449115-e7a0-5eb2-b9b7-90d95badf92e
  labels:
    privileged-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    privileged-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    privileged-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    pss.security.kolteq.com/audit: 'baseline-restricted'
    pss.security.kolteq.com/enforce: 'baseline-restricted'
    pss.security.kolteq.com/warn: 'baseline-restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods/ephemeralcontainers"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.ephemeralContainers) ||
        object.spec.ephemeralContainers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.privileged) ||
          c.securityContext.privileged == false
        )
      message: >
        Privileged ephemeral containers are disallowed. All
        spec.ephemeralContainers[*].securityContext.privileged must be undefined or false.
