apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: violating-rolebinding-system-group
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
