apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: clusterrole-serviceaccount-tokens
  annotations:
    security.kubeapt.io/displayName: "Serviceaccount Tokens"
    security.kubeapt.io/description: "ClusterRoles must not allow creating serviceaccount/token subresource."
    security.kubeapt.io/resource: "ClusterRoles"
    security.kubeapt.io/severity: "9"
    security.kubeapt.io/remediation: "Remove create on serviceaccounts/token. Fields: rules[*].resources, rules[*].verbs."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - clusterroles
  validations:
  - expression: |
      !has(object.rules) || object.rules.all(r,
        !(has(r.apiGroups) && has(r.resources) && has(r.verbs) &&
          r.apiGroups.exists(ag, ag == "") &&
          r.resources.exists(res, res == "serviceaccounts/token") &&
          r.verbs.exists(v, v in ["create"]))
      )
    message: |
      ClusterRoles must not allow creating serviceaccount/token subresource.
