apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: violating-rolebinding-anonymous
subjects:
- kind: User
  name: system:anonymous
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
