apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: readinessprobe-tcpsocket-host-containers
  annotations:
    security.kubeapt.io/displayName: 'Readinessprobe Tcpsocket Host'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for readinessprobe-tcpsocket-host/containers.
    security.kubeapt.io/resource: Containers
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the readinessprobe-tcpsocket-host/containers policy.
    policies.kolteq.com/validatingAdmissionPolicy: ce711d38-131e-550b-9159-1684162f0707
  labels:
    pss.security.kolteq.com/audit: 'baseline - restricted'
    pss.security.kolteq.com/enforce: 'baseline - restricted'
    pss.security.kolteq.com/warn: 'baseline - restricted'
    readinessprobe-tcpsocket-host-containers.security.kolteq.com/audit: 'false - true'
    readinessprobe-tcpsocket-host-containers.security.kolteq.com/enforce: 'false - true'
    readinessprobe-tcpsocket-host-containers.security.kolteq.com/warn: 'false - true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.readinessProbe) ||
          !has(c.readinessProbe.tcpSocket) ||
          !has(c.readinessProbe.tcpSocket.host) ||
          c.readinessProbe.tcpSocket.host == ""
        )
      message: >
        spec.containers[*].readinessProbe.tcpSocket.host must be undefined or empty ("").
