apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: run-as-group-pod
  annotations:
    security.kubeapt.io/displayName: "Run As Group"
    security.kubeapt.io/description: "spec.securityContext.runAsGroup must be undefined or a non-zero value (> 0)."
    security.kubeapt.io/resource: "Pods"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Set spec.securityContext.runAsGroup to >0 or omit it. Fields: spec.securityContext.runAsGroup."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      !has(object.spec.securityContext) || !has(object.spec.securityContext.runAsGroup) || object.spec.securityContext.runAsGroup > 0
    message: |
      spec.securityContext.runAsGroup must be undefined or a non-zero value (> 0).
