apiVersion: v1
kind: Pod
metadata:
  name: violating-run-as-group-pod
spec:
  securityContext:
    runAsGroup: 0
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
