apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: hostpath-volumes
  annotations:
    security.kubeapt.io/displayName: 'Hostpath Volumes'
    security.kubeapt.io/description: ValidatingAdmissionPolicy for hostpath-volumes.
    security.kubeapt.io/resource: Pods
    security.kubeapt.io/severity: medium
    security.kubeapt.io/remediation: Adjust workloads to satisfy the hostpath-volumes policy.
    policies.kolteq.com/validatingAdmissionPolicy: 442539af-2016-5e89-9049-475db1b41f50
  labels:
    hostpath-volumes.security.kolteq.com/audit: 'false,true'
    hostpath-volumes.security.kolteq.com/enforce: 'false,true'
    hostpath-volumes.security.kolteq.com/warn: 'false,true'
    pss.security.kolteq.com/audit: 'baseline,restricted'
    pss.security.kolteq.com/enforce: 'baseline,restricted'
    pss.security.kolteq.com/warn: 'baseline,restricted'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.volumes) ||
        object.spec.volumes.all(v, !has(v.hostPath))
      message: >
        HostPath volumes are disallowed. Each spec.volumes[*].hostPath must be undefined.
