apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: livenessprobe-tcpsocket-host-containers
  annotations:
    security.kubeapt.io/displayName: "Livenessprobe Tcpsocket Host"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for livenessprobe-tcpsocket-host/containers."
    security.kubeapt.io/resource: "Containers"
    security.kubeapt.io/severity: "3"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the livenessprobe-tcpsocket-host/containers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  validations:
  - expression: |
      object.spec.containers.all(c,
        !has(c.livenessProbe) ||
        !has(c.livenessProbe.tcpSocket) ||
        !has(c.livenessProbe.tcpSocket.host) ||
        c.livenessProbe.tcpSocket.host == ""
      )
    message: |
      spec.containers[*].livenessProbe.tcpSocket.host must be undefined or empty ("").
