apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optout-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/warn: enabled
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/warn
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optin-warn
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optout-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    security.kolteq.com/audit: enabled
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/audit
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optin-audit
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit
        operator: In
        values:
        - 'true'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optout-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    security.kolteq.com/enforce: enabled
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: security.kolteq.com/enforce
        operator: In
        values:
        - enabled
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce
        operator: NotIn
        values:
        - 'false'
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: image-no-latest-ephemeralcontainers-namespace-optin-deny
  annotations:
    policies.kolteq.com/validatingAdmissionPolicy: 04c55983-a52d-5d6b-93be-361f75995a16
  labels:
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/audit: 'false-true'
    check-image-no-latest-ephemeralcontainers.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  policyName: image-no-latest-ephemeralcontainers
  validationActions:
  - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: check-image-no-latest-ephemeralcontainers.security.kolteq.com/enforce
        operator: In
        values:
        - 'true'
