apiVersion: v1
kind: Pod
metadata:
  name: violating-read-only-root-filesystem-initcontainers
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  initContainers:
  - name: init
    image: busybox:1.36
    command: ["sh", "-c", "echo init"]
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: false
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
      appArmorProfile:
        type: RuntimeDefault
      seLinuxOptions:
        user: ""
        role: ""
        type: ""
      procMount: Default
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
      seccompProfile:
        type: RuntimeDefault
      appArmorProfile:
        type: RuntimeDefault
