apiVersion: v1
kind: Pod
metadata:
  name: violating-dns-policy
spec:
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: main
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
