apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: role-rbac-write
  annotations:
    security.kubeapt.io/displayName: 'Rbac Write'
    security.kubeapt.io/description: Roles must not grant write/bind/escalate permissions on RBAC resources.
    security.kubeapt.io/resource: Roles
    security.kubeapt.io/severity: "9"
    security.kubeapt.io/remediation: "Remove write/bind/escalate on RBAC resources. Fields: rules[*].apiGroups, rules[*].resources, rules[*].verbs."
    policies.kolteq.com/validatingAdmissionPolicy: 1dea3c88-4df7-5d0d-9dfc-babfc0db4022
  labels:
    check-role-rbac-write.security.kolteq.com/audit: 'false-true'
    check-role-rbac-write.security.kolteq.com/enforce: 'false-true'
    check-role-rbac-write.security.kolteq.com/warn: 'false-true'
    security.kolteq.com/audit: enabled
    security.kolteq.com/enforce: enabled
    security.kolteq.com/warn: enabled
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - roles
  variables:
  - name: rbacResources
    expression: |
      ["roles","rolebindings","clusterroles","clusterrolebindings"]
  - name: rbacWriteVerbs
    expression: |
      ["create","update","patch","delete","bind","escalate"]
  validations:
  - expression: |
      !has(object.rules) || object.rules.all(r,
        !(r.apiGroups.exists(ag, ag == "rbac.authorization.k8s.io") &&
          r.resources.exists(res, variables.rbacResources.exists(rr, rr == res)) &&
          r.verbs.exists(v, variables.rbacWriteVerbs.exists(rv, rv == v))
        )
      )
    message: |
      Roles must not grant write/bind/escalate permissions on RBAC resources.
