apiVersion: v1
kind: Node
metadata:
  name: violating-control-plane
  labels:
    node-role.kubernetes.io/control-plane: ""
spec:
  taints:
  - key: node-role.kubernetes.io/control-plane
    effect: PreferNoSchedule
