apiVersion: v1
kind: ServiceAccount
metadata:
  name: violating-imagepullsecrets-scope
  namespace: policy-test
automountServiceAccountToken: false
imagePullSecrets:
- name: registry-cred-1
- name: registry-cred-2
