apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: seccomp-profile-containers
  annotations:
    security.kubeapt.io/displayName: "Seccomp Profile"
    security.kubeapt.io/description: "ValidatingAdmissionPolicy for seccomp-profile/containers."
    security.kubeapt.io/resource: "Containers"
    security.kubeapt.io/severity: "5"
    security.kubeapt.io/remediation: "Adjust workloads to satisfy the seccomp-profile/containers policy."
    security.kubeapt.io/product: "Kubernetes"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:
      - ''
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
  variables:
  - name: allowedSeccompTypes
    expression: |
      ["RuntimeDefault","Localhost"]
  validations:
  - expression: |
      (has(object.spec.os) &&
       has(object.spec.os.name) &&
       object.spec.os.name.lowerAscii() == "windows") ||
      object.spec.containers.all(c,
        !has(c.securityContext) ||
        !has(c.securityContext.seccompProfile) ||
        !has(c.securityContext.seccompProfile.type) ||
        variables.allowedSeccompTypes.exists(t, t == c.securityContext.seccompProfile.type)
      )
    message: |
      spec.containers[*].securityContext.seccompProfile.type must be undefined, RuntimeDefault, or Localhost.
